# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Docs Deploy

on: [workflow_dispatch]

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # - name: 🧑‍🔧 Get Core Dependencies
      #   uses: ./.github/workflows/actions/get-core-dependencies

      # There is an error with sharp on Node20. This is a workaround to use Node20
      # We need to update Docusaurus to fix this. (same issue locally when using Node22)
      - name: 🧰 Setup Node 20 (LTS)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: "pnpm"

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0

      - name: 🏗️ Install Dependencies
        run: pnpm install

      - name: 🔧 Git Config
        run: git config --global core.autocrlf false

      - run: pnpm run docs
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
          DISTRIBUTION_ID_V6: ${{ secrets.DISTRIBUTION_ID_V6 }}
          DISTRIBUTION_ID_V7: ${{ secrets.DISTRIBUTION_ID_V7 }}
